# Generated by Django 6.1.1 on 2026-10-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateField()),
                ('candidate_name', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_contact_no', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('Interested', 'Interested'), ('Wait for Confirmation', 'Wait for Confirmation'), ('Not-Interested', 'Not-Interested')], max_length=30)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-enquiry_date', '-id'],
            },
        ),
    ]
