# Generated by Django 6.1.1 on 2026-10-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='guardian_contact_no',
        ),
        migrations.AddField(
            model_name='candidate',
            name='counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselled_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_interested',
            field=models.CharField(blank=True, choices=[('Tailoring & Fashion Design', 'Tailoring & Fashion Design'), ('Computer / Tally / Accounts', 'Computer / Tally / Accounts'), ('Beauty & Wellness', 'Beauty & Wellness'), ('Retail & Sales', 'Retail & Sales'), ('Electrician', 'Electrician'), ('Fitter / Welder', 'Fitter / Welder'), ('Industrial Safety', 'Industrial Safety'), ('Logistics & Warehousing', 'Logistics & Warehousing'), ('Solar Technician', 'Solar Technician'), ('Driving (LMV / HMV)', 'Driving (LMV / HMV)'), ('Healthcare Assistant', 'Healthcare Assistant'), ('Hospitality', 'Hospitality'), ('Mobile Repair', 'Mobile Repair'), ('Fish Processing & Value Addition', 'Fish Processing & Value Addition'), ('Spoken English', 'Spoken English')], max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='family_annual_income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, choices=[('Theru Veerapandiya Puram', 'Theru Veerapandiya Puram'), ('A. KumaraReddiyapuram', 'A. KumaraReddiyapuram'), ('T. Kumaragiri', 'T. Kumaragiri'), ('Milavittan', 'Milavittan'), ('Silverpuram', 'Silverpuram'), ('Pandarampatti', 'Pandarampatti'), ('Therespuram', 'Therespuram'), ('Anna Colony', 'Anna Colony'), ('Inigo Nagar', 'Inigo Nagar'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_preference',
            field=models.CharField(blank=True, choices=[('Fresh Skills Required', 'Fresh Skills Required'), ('Skilled only Certificate required', 'Skilled only Certificate required')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Below 5', 'Below 5'), ('5-9', '5-9'), ('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Interested', 'Interested'), ('Non-Interested', 'Non-Interested'), ('Yet to Confirm', 'Yet to Confirm')], max_length=30),
        ),
    ]
