# Generated by Django 6.1.1 on 2026-10-03 12:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_remove_candidate_dob_remove_candidate_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('candidate_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calling_task', to='students.candidate')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calling_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
            },
        ),
    ]
