# Generated by Django 6.1.1 on 2026-10-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_counsellor_names(apps, schema_editor):
    CallingTask = apps.get_model('calling', 'CallingTask')
    User = apps.get_model('auth', 'User')
    users = {
        user.pk: (' '.join(part for part in (user.first_name, user.last_name) if part).strip() or user.username)
        for user in User.objects.all()
    }
    for task in CallingTask.objects.exclude(counsellor_id=None).only('id', 'counsellor_id').iterator():
        CallingTask.objects.filter(pk=task.pk).update(
            counsellor_name_snapshot=users.get(task.counsellor_id, '')
        )


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callingtask',
            name='counsellor_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(preserve_counsellor_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='callingtask',
            name='counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calling_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
