# Generated by Django 6.1.1 on 2026-10-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0002_callingtask_counsellor_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Revoked', 'Revoked')], default='Pending', max_length=20),
        ),
    ]
